# Generated by Django 6.1.1 on 2026-09-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Combo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Combo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Especial (R$)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Ativo no Cardápio')),
            ],
            options={
                'verbose_name': 'Combo Promocional',
                'verbose_name_plural': 'Combos Promocionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número da Mesa')),
                ('capacidade', models.PositiveIntegerField(default=4, verbose_name='Capacidade de Pessoas')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='livre', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Prato')),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('principal', 'Prato Principal'), ('sobremesa', 'Sobremesa'), ('bebida', 'Bebida')], default='principal', max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição dos Ingredientes')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Pedido')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Cliente / Responsável')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status da Comanda')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Atendimento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='cardapio.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário (R$)')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação (ex: sem cebola)')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cardapio.comanda', verbose_name='Comanda')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.combo', verbose_name='Combo Escolhido')),
                ('prato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.prato', verbose_name='Prato Escolhido')),
            ],
            options={
                'verbose_name': 'Item da Comanda',
                'verbose_name_plural': 'Itens da Comanda',
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='pratos',
            field=models.ManyToManyField(related_name='combos', to='cardapio.prato', verbose_name='Pratos Inclusos'),
        ),
    ]
